# Maven build with sonar
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "klaushauschild1984-github"
    token:
      secure: ""
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'