# Maven build with sonar
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "klaushauschild1984-github"
    token:
      secure: "ImCxLxe1/AN0q4hgH7fnMDCXC4nn0zgMR4p+0Ljt/VJTKh4RQB3tQNLQvJUxOw7X4P1R8A54vJ4VNFrdze1gGvLQpT3TxUGHlJx1yuXpBnwmym1boIgcRceQajaAXnfuidN0hygmk0WwknM6cZV1iDhavQcO7QL0Rly7erV0IGqi8jxpFI1b2cU3oqd7qQcrIgC0LX0jdMFLPdEVwz1I1/aWqvoHS/m5AEiwQSWfQwC0guP2if6qlVRrgoLl+79ELZLbLidhxu9daLcF8MF1Zq9qk78FIos/7MUgB3+gA0vBSUlvua6/Tc0V14VWBkC2G/FRnL44V5Lxj6jFuTXS5gpNmVhv4ZubTcz2qIp8mWuhMohahr0iJT14RQSTSy2MpMFRQcUXabmkeo+GxDKu6WHwXCmN42T42VrOJrkHqDsUigcjEAV3ZaTqzOTD9VUT2LZ1H38dwHlmMztfhiG6YVimP+bhFFXAchf6m6bfx+nT2VUE3cGEv3THijFtwoLvpoejN84XCtJF51hNzxpGuvWfDyAinFGQvwrRYvryWK2nfbqPTqtJmId904PvFR78D4GmloiPaiHHZBqAuHPohRpgYZ4RKoPdAGtSNcn7Gs4nlzfbd9/1CiB+gKl2AKbByQQr64lJdIJr7mb7RlIj0zovV+s5Q1UbzTSfn4EiCiQ="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -DskipTests
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'